# osx_image: xcode9.1 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c
cache:
  directories:
    - Carthage
xcode_project: YumeAlamofire.xcodeproj # path to your xcodeproj folder
xcode_scheme: YumeAlamofire
podfile: pod # Disable `pod install`
osx_image: xcode10.1
git:
  depth: 1
  submodules: false
branches:
  only:
    - master
before_script:
  - bundle exec danger
script:
  - set -o pipefail

# after_success:
#   - bash <(curl -s https://codecov.io/bash)