# osx_image: xcode9.1 settings
# https://docs.travis-ci.com/user/reference/osx#Xcode-version
language: swift # or objective-c
cache:
  directories:
    - Carthage
xcode_project: YumeAlamofire.xcodeproj # path to your xcodeproj folder
xcode_scheme: YumeAlamofire
podfile: pod # Disable `pod install`
osx_image: xcode10.1
git:
  depth: 1
  submodules: false
branches:
  only:
    - master
before_install:
  - brew install make carthage
  # - carthage update --platform ios
# install:
env:
  global:
    - RELEASE=Debug
    - SCHEME=YumeAlamofire
    - secure: "WUefOYrG4nqF437c23IOhh9zikJvBK4r7u+ZkCn/6fjSqDf98HW8Fb1hU8mcXt90Eq4gqnn30PghlVigIiZlduU4+RJ+hWKneW7sABn7CUhfM57SFBCHEIPrGWgfhA7uS/PUCYGpCgzzuDLgcys4bJBIpQknXsKueJvgO/BxAZm8HOZTzRFP31ekxvo7cSicfkEU9GL4J+Gwxx219uHoIMSliMnERsbtu1WP6uY7m655FGLjk5vhabFgwOYUhN6REIlu1KpFvC7uUUng7pKBaKZLYQysZywrEpTD/1XBRpn8IPntw8SKmHz5h2M4DIW4mhSCxS4TciQcxH2XL+7XNM9i//HBmatx+9p8CaoNmbc1UN4vfcO0rf1aQrCX8tEU3lSyi5uZ/qwnINO2GJDYEy/q7GS6yRNKhSvMRwumjoUuD9p81UDVi4kknXIoqgJnXEcK12a1mU4LmxdVjXUaALB+DKKbiPDps+DUFeGtJ+6ZhinxUilGWpVLFjeOuCOdfpW+wjrBjSXURNMhfOHtMGB/XpcI2/Hq2sgzzn2sdL3Io2c0c/9Ji6WnX2jmrWsn9AK2h5N0QI71/wqxQaej1GmapxiW7h5oFUMI0w1Et6SDGfweV65NteecfSoDi8mgLpcCCriZ4IPY5771E0aTSOxdo05RmWVEWdNZQKkLY/g="
  matrix:

    # - SDK=macosx
    #   DESTINATION='platform=OS X,arch=x86_64'
    #   USE_MAKE="NO"
    #   MAKE_TARGET=""

    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=11.3,name=iPhone X'
      USE_MAKE="NO"
      MAKE_TARGET=""
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=10.3.1,name=iPhone 7 Plus'
      USE_MAKE="NO"
      MAKE_TARGET=""
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=9.3,name=iPhone 6'
      USE_MAKE="NO"
      MAKE_TARGET=""
    - SDK=iphonesimulator
      DESTINATION='platform=iOS Simulator,OS=9.0,name=iPhone 6'
      USE_MAKE="NO"
      MAKE_TARGET=""
    
    # - SDK=""
    #   DESTINATION=""
    #   USE_MAKE="YES"
    #   MAKE_TARGET="carthage"

    - SDK=""
      DESTINATION=""
      USE_MAKE="YES"
      MAKE_TARGET="pod"
    
    - SDK=""
      DESTINATION=""
      USE_MAKE="YES"
      MAKE_TARGET="spm"

      # appletvsimulator12.0
      # watchsimulator5.0

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - instruments -s devices

  - if [ $USE_MAKE == "YES" ]; then
      make $MAKE_TARGET;
    else
      carthage build --cache-builds --platform ios;
      xcodebuild -project $SCHEME.xcodeproj -scheme $SCHEME -configuration $RELEASE -sdk $SDK -destination "$DESTINATION" clean build test | xcpretty;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)